# Generated by Django 5.2 on 2025-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reddit_wsb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('score', models.IntegerField()),
                ('comms_num', models.IntegerField()),
                ('body', models.TextField()),
                ('date', models.TextField()),
                ('stock', models.CharField(max_length=10)),
                ('title_unstemmed_sentiment', models.FloatField()),
                ('body_unstemmed_sentiment', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('title', 'date')},
            },
        ),
    ]
