# Generated by Django 5.2 on 2025-08-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_reddit_wsb'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('tickers', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('total_results', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='api_v1_news_cache_k_5959e8_idx'), models.Index(fields=['expires_at'], name='api_v1_news_expires_bebc4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_to_image', models.URLField(blank=True, max_length=500, null=True)),
                ('article_order', models.PositiveIntegerField()),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api_v1.newscache')),
            ],
            options={
                'ordering': ['cache', 'article_order'],
                'indexes': [models.Index(fields=['cache', 'article_order'], name='api_v1_news_cache_i_35c60c_idx'), models.Index(fields=['published_at'], name='api_v1_news_publish_e87b2d_idx')],
                'unique_together': {('cache', 'url')},
            },
        ),
    ]
