# Generated by Django 5.2 on 2025-08-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_newscache_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('market_index', models.CharField(max_length=10)),
                ('indicator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='api_v1_port_cache_k_49dcdb_idx'), models.Index(fields=['expires_at'], name='api_v1_port_expires_425874_idx'), models.Index(fields=['start_date', 'end_date'], name='api_v1_port_start_d_33d19a_idx'), models.Index(fields=['indicator'], name='api_v1_port_indicat_3f0247_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portfolio_return', models.FloatField(blank=True, null=True)),
                ('benchmark_return', models.FloatField(blank=True, null=True)),
                ('cumulative_portfolio_return', models.FloatField(blank=True, null=True)),
                ('cumulative_benchmark_return', models.FloatField(blank=True, null=True)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api_v1.portfoliocache')),
            ],
            options={
                'ordering': ['cache', 'date'],
                'indexes': [models.Index(fields=['cache', 'date'], name='api_v1_port_cache_i_96e814_idx')],
                'unique_together': {('cache', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='api_v1.portfoliocache')),
            ],
            options={
                'ordering': ['cache', 'date', 'ticker'],
                'indexes': [models.Index(fields=['cache', 'date'], name='api_v1_port_cache_i_7b3342_idx')],
                'unique_together': {('cache', 'date', 'ticker')},
            },
        ),
    ]
