# Generated by Django 5.2 on 2025-08-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_portfoliocache_portfolioreturn_portfolioticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIndicatorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('indicator', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['month_year', 'indicator'], name='api_v1_mont_month_y_86e2ab_idx'), models.Index(fields=['expires_at'], name='api_v1_mont_expires_63fde9_idx')],
                'unique_together': {('month_year', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyIndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('score_value', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api_v1.monthlyindicatorcache')),
            ],
            options={
                'ordering': ['cache', 'rank'],
                'indexes': [models.Index(fields=['cache', 'rank'], name='api_v1_mont_cache_i_91e54c_idx'), models.Index(fields=['ticker'], name='api_v1_mont_ticker_a4e6e2_idx')],
                'unique_together': {('cache', 'ticker')},
            },
        ),
    ]
