# Generated by Django 5.2 on 2025-08-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_monthlyindicatorcache_monthlyindicatorscore'),
    ]

    operations = [
        # Delete all old portfolio cache data first
        migrations.RunSQL("DELETE FROM api_v1_portfolioticker;", reverse_sql=""),
        migrations.RunSQL("DELETE FROM api_v1_portfolioreturn;", reverse_sql=""),
        migrations.RunSQL("DELETE FROM api_v1_portfoliocache;", reverse_sql=""),
        
        # Now delete the models
        migrations.DeleteModel(
            name='PortfolioTicker',
        ),
        migrations.DeleteModel(
            name='PortfolioReturn',
        ),
        migrations.DeleteModel(
            name='PortfolioCache',
        ),
    ]
